### ISSUE TITLE
Lesson 1B: missing word

### ISSUE THREAD

**Issue by lvdbrink** [geo4web-testbed/lessons-learned#2]
A word or words seem to be missing here:

"do not bother users with specialist features, data or _in your their knowledge and skills_. "

https://github.com/geo4web-testbed/lessons-learned/wiki/Lesson-1B:-Keep-it-simple

**Comment by adbgnm** [comment]
Typo ; changed to: Because different users have different expertise, knowledge and skills. So, do not bother users with specialist features or data.
