### ISSUE TITLE
Lesson 2: time to first succesful call is meant differently

### ISSUE THREAD

**Issue by lvdbrink** [geo4web-testbed/lessons-learned#3]
Lesson 2 mentiones the concept of 'time to first succesful call'. This is however meant differently by Dimitri van Hees who coined the term. What he means is the time it takes a developer to understand an API well enough to succesfully interact with it for the first time. It should be somewhere in Lesson 3, not 2. See also https://github.com/geo4web-testbed/topic3/wiki/Developer-Experience.

https://github.com/geo4web-testbed/lessons-learned/wiki/Lesson-2:-Make-search-engines-feel-comfortable-to-discover-you

**Comment by adbgnm** [comment]
Solved... 2A and 3A are edited.... Time To First Succesfull Call added to 3A, and deleted from 2A.
