### ISSUE TITLE
Lesson 2B: link not working

### ISSUE THREAD

**Issue by lvdbrink** [geo4web-testbed/lessons-learned#4]
The link to ldproxy.net is not working. 

https://github.com/geo4web-testbed/lessons-learned/wiki/Lesson-2B:-Foster-to-link-everything-with-everything

**Comment by cportele** [comment]
Yes, we are having some problems today with the server that we are trying to fix. (cc: @azahnen)

**Comment by cportele** [comment]
The link is working again.
